bat_roost/bat_roost/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView
from allauth.account.views import confirm_email, email_verification_sent

urlpatterns = [
    path('admin/', admin.site.urls),
    path('submission/', include('submission.urls')),
    path('forgot_password/', PasswordResetView.as_view(), name="password_reset"),
    path('password_reset_done/', PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset_password/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('', include('core.urls')),
    re_path(r'^rest-auth/', include('rest_auth.urls')),
    re_path(r'rest-auth/registration/', include('rest_auth.registration.urls')),
    re_path(
        r"^confirm-email/(?P<key>[-:\w]+)/$",
        confirm_email,
        name="account_confirm_email",
    ),
    path(
        "confirm-email/",
        email_verification_sent,
        name="account_email_verification_sent",
    ), # Renders Template only 
]

bat_roost/core/api/urls.py
from django.urls import path

from core.api.views import UserDataAPIView, EmailConfirmationAPIView, LoginApiView


app_name = "core"


urlpatterns = [
    path("login/", LoginApiView.as_view(), name='api-login'),
    path("user/", UserDataAPIView.as_view(), name="api-details"),
    path("email_confirmation/", EmailConfirmationAPIView.as_view(), name="api-confirm-email")
]

bat_roost/core/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from core.views import AdminLoginView, ThanksView, EmailConfirmedView, download_users

app_name = "core"

endpoint = "api/v1/"


urlpatterns = [
    path('login/', AdminLoginView.as_view(), name="login"),
    path('thanks/', ThanksView.as_view(), name="thanks"),
    path(endpoint, include('core.api.urls')),
    path(endpoint + "submission/", include('submission.api.urls')),
    path("email_confirmed/",EmailConfirmedView.as_view(), name="email_confirmed"),
    path("download_user/",download_users, name="download_user"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bat_roost/core/models.py
from allauth.account.signals import email_confirmed
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.dispatch import receiver

class User(AbstractUser):
    is_admin = models.BooleanField(default=False)
    is_verified = models.BooleanField(default=False)
    contact_no = models.CharField(max_length=12)
    locality = models.CharField(max_length=255)


@receiver(email_confirmed)
def email_confirmed_(request, email_address, **kwargs):
    user = email_address.user
    user.is_verified = True
    user.save()

bat_roost/core/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

class AdminAuthForm(AuthenticationForm):

    def confirm_login_allowed(self, user):
        if not user.is_admin:
            raise ValidationError(
                _("This is not an admin account"),
                code="non_admin",
            )

        return super(AdminAuthForm, self).confirm_login_allowed(user)

bat_roost/core/api/views.py
from rest_auth.views import LoginView
from rest_framework.generics import RetrieveUpdateAPIView
from rest_framework.views import APIView
from rest_framework import status
from rest_framework.response import Response

from allauth.account.utils import send_email_confirmation
from rest_framework.permissions import IsAuthenticated
# from django.utils.translation import ugettext_lazy as _
# from rest_auth.views import LoginView
from core.api.serializers import UserDataSerializer
# from core.api.serializers import LoginApiSerializers
from core.models import User

# class EmailVerifiedPermission(BasePermission):
#     message = "Email is not verified"
#     def has_permission(self, request, view):
#         # print(request.user.is_verified)
#         print(request.user)
#         if request.method in SAFE_METHODS:
#             return True
#         if request.user.is_authenticated:
#             print(request.user.is_verified)
#             print("Hello")
#             if not request.user.is_verified:
#                 print(request.user.is_verified)
#                 return False
#         return True
#
#     def has_object_permission(self, request, view, obj):
#         print("Hello")
#         return not obj.user.is_verified


class UserDataAPIView(RetrieveUpdateAPIView):
    permission_classes = [IsAuthenticated]
    queryset = User.objects.all()
    serializer_class = UserDataSerializer

    def get_object(self):
        return self.request.user



class EmailConfirmationAPIView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        if request.user.is_verified:
            return Response({'message': 'Email already verified'}, status=status.HTTP_201_CREATED)

        send_email_confirmation(request, request.user)
        return Response({'message': 'Email confirmation sent'}, status=status.HTTP_201_CREATED)



class LoginApiView(LoginView):

    def post(self, request, *args, **kwargs):
        self.request = request
        try:
            if self.request.data.get("username"):
                user = User.objects.get(username=self.request.data["username"])
            elif self.request.data.get("email"):
                user = User.objects.get(email=self.request.data["email"])
            if not user.is_verified:
                send_email_confirmation(request, user)
                return Response({'non_field_errors': ['Email not Verified. Email confirmation sent']}, status=status.HTTP_403_FORBIDDEN)
        except:
            pass
        self.serializer = self.get_serializer(data=self.request.data,
                                              context={'request': request})
        self.serializer.is_valid(raise_exception=True)

        self.login()
        return self.get_response()

bat_roost/core/views.py
import csv

from core.forms import AdminAuthForm
from core.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.http import HttpResponse
from django.views.generic import View
from django.views.generic.base import TemplateView
from submission.models import Submission


# Create your views here.
class AdminLoginView(LoginView):
    authentication_form = AdminAuthForm
    template_name = "core/admin_login.html"


class ThanksView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        return HttpResponse("Thanks " + request.user.username)


class EmailConfirmedView(TemplateView):
    template_name = "core/email_confirmed.html"


def download_users(request):
    user_list = User.objects.all()
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="submission.csv"'
    writer = csv.writer(response, delimiter=',')
    writer.writerow(['id', 'email', 'first_name', 'last_name',
                     'is_admin', 'contact_no', 'locality', 'is_verified', 'submissions', 'accepted', 'rejected'])
    for obj in user_list:
        submission_list = obj.submission_set.all()
        total_count = submission_list.count()
        accepted_count = submission_list.filter(status=Submission.ACCEPTED).count()
        rejected_count = submission_list.filter(status=Submission.REJECTED).count()
        row_to_add = [obj.pk, obj.email, obj.first_name, obj.last_name, obj.is_admin, obj.contact_no, obj.locality,
                      obj.is_verified, total_count, accepted_count, rejected_count]
        writer.writerow(row_to_add)
    return response

bat_roost/templates/core/admin_login.html
{% load static %}
{% load core_tags %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Login Page</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/admin_login.css' %}">
</head>

<body class="my-login-page">
    <section class="h-100">
        <div class="container h-100">
            <div class="row justify-content-md-center h-100">
                <div class="card-wrapper">
                    <div class="brand">
                        <img src="{% static 'img/bcit_logo.png' %}" alt="logo">
                    </div>
                    <div class="card fat">
                        <div class="card-body">
                            <h4 class="card-title">Login</h4>
                            <form method="POST" class="my-login-validation" novalidate="">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="username">Username</label>
                                    {{ form.username|add_class:"form-control" }}
                                    <!-- <input id="username" type="text" class="form-control" name="username" value="" required autofocus> -->
                                    <div class="invalid-feedback">
                                        Email is invalid
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="password">Password
                                        <a href="{% url 'password_reset' %}" class="float-right">
                                            Forgot Password?
                                        </a>
                                    </label>
                                    {{ form.password|add_class:"form-control" }}
                                    <div class="invalid-feedback">
                                        Password is required
                                    </div>
                                </div>

                                <!-- <div class="form-group">
									<div class="custom-checkbox custom-control">
										<input type="checkbox" name="remember" id="remember" class="custom-control-input">
										<label for="remember" class="custom-control-label">Remember Me</label>
									</div>
								</div> -->
                                <div class="errors text-danger"> <b>{{form.errors}}</b></div>
                                {% if messages %}
                                <ul class="messages">
                                    {% for message in messages %}
                                    <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                                        {% endfor %}
                                </ul>
                                {% endif %}
                                <div class="form-group m-0">
                                    <button type="submit" class="btn btn-primary btn-block">
                                        Login
                                    </button>
                                </div>

                            </form>
                        </div>
                    </div>
                    <div class="footer">
                        Copyright &copy; 2021 &mdash; BCIT
                    </div>
                </div>
            </div>
        </div>
    </section>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="{% static 'js/admin_login.js' %}"></script>
</body>


</html>

bat_roost/templates/core/admin_login_old.html
<html>
<body>
{% if user.is_authenticated %}
    {{ user.username }}
{% endif %}
{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'core:login' %}">
{% csrf_token %}
{{form.errors}}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login">
<input type="hidden" name="next" value="{{ next }}">
</form>
</body>
</html>

bat_roost/templates/core/email_confirmed.html
{% load static %}
{% load core_tags %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Login Page</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/admin_login.css' %}">
</head>

<body class="my-login-page">
    <section class="h-100">
        <div class="container h-100">
            <div class="row justify-content-md-center h-100">
                <div class="">
                    <div class="brand">
                        <img src="{% static 'img/bcit_logo.png' %}" alt="logo">
                    </div>
                    <div class="card fat">
                        <div class="card-body">
                            <h3 class="card-title">Email has been successfully confirmed. You can now login through the app</h3>
                        </div>
                    </div>
                    <div class="footer">
                        <strong>Copyright &copy; 2021 &mdash; BCIT</strong>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="{% static 'js/admin_login.js' %}"></script>
</body>


</html>