bat_roost/bat_roost/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView
from allauth.account.views import confirm_email, email_verification_sent

urlpatterns = [
    path('admin/', admin.site.urls),
    path('submission/', include('submission.urls')),
    path('forgot_password/', PasswordResetView.as_view(), name="password_reset"),
    path('password_reset_done/', PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset_password/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('', include('core.urls')),
    re_path(r'^rest-auth/', include('rest_auth.urls')),
    re_path(r'rest-auth/registration/', include('rest_auth.registration.urls')),
    re_path(
        r"^confirm-email/(?P<key>[-:\w]+)/$",
        confirm_email,
        name="account_confirm_email",
    ),
    path(
        "confirm-email/",
        email_verification_sent,
        name="account_email_verification_sent",
    ), # Renders Template only 
]

bat_roost/core/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from core.views import AdminLoginView, ThanksView, EmailConfirmedView, download_users

app_name = "core"

endpoint = "api/v1/"


urlpatterns = [
    path('login/', AdminLoginView.as_view(), name="login"),
    path('thanks/', ThanksView.as_view(), name="thanks"),
    path(endpoint, include('core.api.urls')),
    path(endpoint + "submission/", include('submission.api.urls')),
    path("email_confirmed/",EmailConfirmedView.as_view(), name="email_confirmed"),
    path("download_user/",download_users, name="download_user"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bat_roost/submission/api/urls.py
from django.urls import path
from submission.api import views

app_name = "submission"


urlpatterns = [
    path("list/", views.SubmissionListApiView.as_view(), name="list"),
    path("create/", views.SubmissionCreateAPIView.as_view(), name="create"),
    path("details/", views.SubmissionDetailApiView.as_view(), name="details"),
    path("download/", views.SubmissionListDownloadApiView.as_view(), name="details"),
    path("species_list/", views.SpeciesApiView.as_view(), name="species_list")
]

bat_roost/submission/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from .views import AllSubmissionView, AcceptedSubmissionView, ReviewSubmissionView, \
                    AllSubmissionDetails, StatusView,DownloadSubmission,LocationView


app_name = "submission"

urlpatterns = [
    path('all/',AllSubmissionView.as_view(),name='AllSubmissionView'),
    path('accepted/', AcceptedSubmissionView.as_view(), name="AcceptedSubmissionView"),
    path('review/', ReviewSubmissionView.as_view(), name="ReviewSubmissionView"),
    url(r'^all/(?P<pk>\d+)/$', AllSubmissionDetails.as_view(), name='detail'),
    path('change_status/',StatusView.as_view(), name="status_update"),
    path('download/',DownloadSubmission,name='DownloadSubmission'),
    path("loc/",LocationView.as_view(),name="loc"),
    
]

bat_roost/submission/forms.py
from django import forms

from .models import Submission


class UserStatus(forms.ModelForm):
    class Meta:
        model = Submission
        fields = ('status')

bat_roost/submission/api/views.py
import csv
import json

from django.contrib.gis.geos import Point
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from rest_framework import status
from rest_framework.generics import CreateAPIView, ListAPIView, RetrieveAPIView
from rest_framework.parsers import FormParser, MultiPartParser
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from submission.api.serializers import SubmissionSerializer, ImageCreateSerializer, SpeciesSerializer
from submission.models import Submission, Species


class SubmissionCreateAPIView(CreateAPIView):
    permission_classes = [IsAuthenticated]
    parser_classes = (MultiPartParser, FormParser)
    serializer_class = SubmissionSerializer

    def create(self, request, *args, **kwargs):
        if "latitude" not in request.data or "longitude" not in request.data:
            return Response({"non_field_errors": "Position is required"}, status=status.HTTP_400_BAD_REQUEST)

        try:
            latitude = float(request.data["latitude"].strip(" "))
            longitude = float(request.data["longitude"].strip(" "))
        except TypeError:
            return Response("Invalid Values for position", status=status.HTTP_400_BAD_REQUEST)

        species_id = []
        if self.request.data.get("species", ):
            try:
                species_list = json.loads(self.request.data.get("species", ))
                if type(species_list) is not list:
                    return Response("Invalid Values for species. Not a List", status=status.HTTP_400_BAD_REQUEST)

                species_id = [int(x) for x in species_list]
            except ValueError as e:
                print(e)
                return Response("Invalid Values for species", status=status.HTTP_400_BAD_REQUEST)

        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer, latitude=latitude,
                            longitude=longitude, species_id=species_id)
        headers = self.get_success_headers(serializer.data)
        return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)

    def perform_create(self, serializer, **kwargs):
        print(self.request.data)
        serializer.is_valid(raise_exception=True)
        point = Point(x=kwargs["longitude"], y=kwargs["latitude"])
        obj = serializer.save(user=self.request.user, location=point)
        obj_id = obj.id
        images = dict(self.request.data.lists())['images']
        arr = []
        if kwargs.get("species_id"):
            species_id = kwargs["species_id"]
            current_specie = Species.objects.filter(pk__in=species_id)
            for specie in current_specie:
                obj.species.add(specie)

        for img_name in images:
            modified_data = modify_input_for_multiple_files(obj_id,
                                                            img_name)
            file_serializer = ImageCreateSerializer(data=modified_data)
            if file_serializer.is_valid(raise_exception=True):
                file_serializer.save()
                arr.append(file_serializer.data)


class SubmissionListApiView(ListAPIView):
    permission_classes = [IsAuthenticated]
    serializer_class = SubmissionSerializer

    def get_queryset(self):
        return Submission.objects.filter(user=self.request.user)


class SpeciesApiView(ListAPIView):
    serializer_class = SpeciesSerializer
    pagination_class = None

    def get_queryset(self):
        return Species.objects.all()


class SubmissionDetailApiView(RetrieveAPIView):
    permission_classes = [IsAuthenticated]
    serializer_class = SubmissionSerializer

    def get_object(self):
        return get_object_or_404(Submission, pk=self.request.GET.get("pk", ))


class SubmissionListDownloadApiView(ListAPIView):
    permission_classes = [IsAuthenticated]

    def get(self, request, **kwargs):
        items = Submission.objects.filter(
            status=Submission.ACCEPTED, user=request.user)
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="submission.csv"'
        writer = csv.writer(response, delimiter=',')
        writer.writerow(['user', 'description', 'approx_bats',
                         'submission_time', 'photo_taken_time'])

        for obj in items:
            writer.writerow([obj.user, obj.description, obj.approx_bats,
                             obj.submission_time, obj.photo_taken_time])

        return response


def modify_input_for_multiple_files(property_id, image):
    dict = {'submission': property_id, 'image': image}
    return dict

bat_roost/submission/views.py
from django.shortcuts import render, HttpResponse
from django.views.generic.base import TemplateView
from submission.models import Submission, SubmissionImage, Species
from django.views import View
from django.views.generic import ListView, DetailView
from django.http import JsonResponse
from django.core.paginator import Paginator
from django.core.paginator import EmptyPage
from django.core.paginator import PageNotAnInteger
from django.shortcuts import get_object_or_404
import csv
import json
from django.core.serializers import serialize
from core.permission import IsUserAdminTestMixin
from core.misc_functions import is_int_convertible

class AllSubmissionDetails(IsUserAdminTestMixin, DetailView):
    model = Submission
    template_name = "submission/sub_det.html"

    def get_context_data(self, **kwargs):
        """Return the view context data."""
        context = super().get_context_data(**kwargs)
        pk = self.kwargs.get('pk')
        context["markers"] = json.loads(serialize("geojson", Submission.objects.filter(pk=pk)))
        context["domain"] = self.request.META['HTTP_HOST']
        return context


class AllSubmissionView(IsUserAdminTestMixin, ListView):
    model = Submission
    paginate_no = 10
    template_name = 'submission/all_sub.html'

    def get_context_data(self, **kwargs):
        search_params = ""
        context = super(AllSubmissionView, self).get_context_data(**kwargs)
        # submission_list = self.get_queryset()
        submission_list = Submission.objects.all()
        context["filter_status"] = self.request.GET.get("status", )
        if self.request.GET.get("status", ) == "Accepted":
            submission_list = submission_list.filter(status=Submission.ACCEPTED)
            search_params += "status=Accepted&"
        if self.request.GET.get("status", ) == "UnderReview":
            submission_list = submission_list.filter(status=Submission.UNDER_REVIEW)
            search_params += "status=UnderReview&"
        pk = self.request.GET.get("pk", )
        if is_int_convertible(pk):
            submission_list = submission_list.filter(user__pk=pk)
            context["filter_pk"] = pk
            search_params += ("pk=" + pk + "&")
        group1 = self.request.GET.get("group1", )
        context["filter_group1"] = group1
        if group1:
            search_params += "group1={param}&".format(param=group1)
            if group1 == "st":
                submission_list = submission_list.order_by("submission_time")
            if group1 == "pt":
                submission_list = submission_list.order_by("photo_taken_time")

        species_id = self.request.GET.get("species", )
        if is_int_convertible(species_id):
            if int(species_id) == -1:
                # Get submissions with unidentified species
                submission_list = submission_list.filter(species=None)
            else:
                submission_list = submission_list.filter(species__id=species_id)
            context["species"] = species_id
            search_params += "species={param}&".format(param=species_id)
        context["search_params"] = search_params
        context["species_list"] = Species.objects.all()

        paginator = Paginator(submission_list, self.paginate_no)
        if paginator.num_pages > 1:
            context["is_paginated"] = True
        page = self.request.GET.get('page', )
        try:
            submissions = paginator.page(page)
        except PageNotAnInteger:
            submissions = paginator.page(1)
        except EmptyPage:
            submissions = paginator.page(paginator.num_pages)

        context['submission_list'] = submissions
        context['page_obj'] = submissions
        return context


class AcceptedSubmissionView(AllSubmissionView):
    template_name = 'submission/sub_accept.html'

    def get_queryset(self, *args, **kwargs):
        return Submission.objects.filter(status=Submission.ACCEPTED)


class ReviewSubmissionView(AllSubmissionView):
    template_name = 'submission/sub_ur.html'

    def get_queryset(self, *args, **kwargs):
        return Submission.objects.filter(status=Submission.UNDER_REVIEW)


class StatusView(IsUserAdminTestMixin, View):
    def get(self, request):
        obj = get_object_or_404(Submission, id=request.GET.get("id", ))
        return JsonResponse({
            "id": obj.id,
            "status": obj.status,
            "status_options": Submission.STATUS_CHOICES,
        })

    def post(self, request):
        obj = get_object_or_404(Submission, id=request.POST.get("id", ))
        status = request.POST.get("status", )
        review = request.POST.get("review", )
        if not Submission.is_valid_status(status):
            return JsonResponse({
                "success": False,
                "message": "Invalid status code",
            }, status=400)

        obj.status = status
        obj.review = review
        obj.save()
        return JsonResponse({
            "success": True,
            "status": obj.status,
            "status_display": obj.get_status_display(),
        })


def DownloadSubmission(request):
    submission_list = Submission.objects.all()
    if request.GET.get("status", ) == "Accepted":
        submission_list = submission_list.filter(status=Submission.ACCEPTED)
    if request.GET.get("status", ) == "UnderReview":
        submission_list = submission_list.filter(status=Submission.UNDER_REVIEW)
    pk = request.GET.get("pk", )
    if is_int_convertible(pk):
        submission_list = submission_list.filter(user__pk=pk)
    if request.GET.get("group1", ) == "st":
        submission_list = submission_list.order_by("submission_time")
    if request.GET.get("group1", ) == "pt":
        submission_list = submission_list.order_by("photo_taken_time")
    species_id = request.GET.get("species", )
    if is_int_convertible(species_id):
        if int(species_id) == -1:
            # Get submissions with unidentified species
            submission_list = submission_list.filter(species=None)
        else:
            submission_list = submission_list.filter(species__id=species_id)
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="submission.csv"'
    writer = csv.writer(response, delimiter=',')

    writer.writerow(['id', 'user', 'description', 'approx_bats',
                     'submission_time', 'photo_taken_time', 'status', 'latitude', 'longitude', 'species', 'image1',
                     'image2', 'image3', 'image4', 'image5'])
    for obj in submission_list:
        species_string = ", ".join(str(specie.name) for specie in obj.species.all())

        row_to_add = [obj.pk, obj.user, obj.description, obj.approx_bats,
                      obj.submission_time, obj.photo_taken_time, obj.status, obj.latitude, obj.longitude,
                      species_string]
        for image in obj.images.all():
            row_to_add.append(request.build_absolute_uri(image.image.url))
        writer.writerow(row_to_add)
    return response





class LocationView(TemplateView):
    model = Submission
    template_name = 'submission/loc.html'

    def get_context_data(self, **kwargs):
        """Return the view context data."""
        context = super().get_context_data(**kwargs)
        submission_list = Submission.objects.all()
        if self.request.GET.get("status", ) == "Accepted":
            submission_list = submission_list.filter(status=Submission.ACCEPTED)
        if self.request.GET.get("status", ) == "UnderReview":
            submission_list = submission_list.filter(status=Submission.UNDER_REVIEW)
        pk = self.request.GET.get("pk", )
        if is_int_convertible(pk):
            submission_list = submission_list.filter(user__pk=pk)
        group1 = self.request.GET.get("group1", )
        if group1:
            if group1 == "st":
                submission_list = submission_list.order_by("submission_time")
            if group1 == "pt":
                submission_list = submission_list.order_by("photo_taken_time")

        species_id = self.request.GET.get("species", )
        if is_int_convertible(species_id):
            if int(species_id) == -1:
                # Get submissions with unidentified species
                submission_list = submission_list.filter(species=None)
            else:
                submission_list = submission_list.filter(species__id=species_id)
        context["markers"] = json.loads(serialize("geojson", submission_list))
        context["domain"] = self.request.META['HTTP_HOST']
        return context

bat_roost/templates/submission/all_sub.html
{% extends 'submission/base.html' %}
{% load static %}

{% block title %} Submissions {% endblock %}
{% block extra_head %}
    <!-- <script src="{% static 'js/submission.js' %}"></script> -->
{% endblock %}

{% block body_block %}
    <form class="card-panel #e0f2f1 teal lighten-5" method='get'>
        <div style="display:inline-block">
            <h5>Filter options:</h5>

            <div class="input-field col s12" style="height: 20px;width: 200px;display:inline-block">
                <select name="status">
                    <option value="" disabled selected>All submissions</option>
                    <option value="Accepted">Accepted</option>
                    <option value="UnderReview">UnderReview</option>

                </select>
            </div>

            <div style="display:inline-block">
                <h6 style="margin-left: 20px;">Pk value</h6>
            </div>
            <div class="browser-default" style="display:inline-block;min-width: 100px;">
                <input placeholder=" " id="pk" type="number" class="validate"
                       style="margin-left:10px;width:60px" name="pk" value="{{ filter_pk }}" >
            </div>

        </div>

        <div style="display:inline-block;margin-left:50px">

            <h6>Sort by</h6>
            <p>
                <label>
                    <input name="group1" type="radio" value="pt"/>
                    <span>Photo Taken Time</span>

                </label>
            </p>
            <p>
                <label>
                    <input name="group1" type="radio" value="st"/>
                    <span>Submission Time</span>
                </label>
            </p>

        </div>
        <div style="display:inline-block;margin-left:50px">
            <label for="species">Select Species</label>
            <select name="species" id="species">
                <option value="" disabled selected>Choose your option</option>
                <option value="-1">Unidentified</option>
                {% for specie in species_list %}
                    <option value="{{ specie.id }}">{{ specie.name }} ({{ specie.scientific_name }})</option>
                {% endfor %}
            </select>
        </div>


        <button class="btn waves-effect waves-light" type="submit" style="margin-left:25px;">Submit

        </button>


    </form>


    <div class="container">
        <h4></h4>
    </div>
    {% if submission_list %}
        <div class="card z-depth-1 table-wrapper">
            <table id='submission' class="responsive-table striped">
                <tr>
                    <th colspan="2">Id</th>
                    <th colspan="2">User</th>
                    <th colspan="3">Description</th>
                    <th colspan="1">Approx bats</th>
                    <th colspan="2">Submission Time</th>
                    <th colspan="2">Photo taken time</th>
                    <th colspan="2">Status</th>

                </tr>
                {% for submission in submission_list %}
                    <tr>
                        <td colspan="2"><a href="{{ submission.id }}/">{{ submission.pk }}</a></td>
                        <td colspan="2"><a href="{{ submission.id }}/">{{ submission.user }}</a></td>
                        <td colspan="3">{{ submission.description }}</td>
                        <td colspan="1">{{ submission.approx_bats }}</td>
                        <td colspan="2">{{ submission.submission_time }}</td>
                        <td colspan="2">{{ submission.photo_taken_time }}</td>
                        <td id="status{{ submission.id }}" colspan="2">{{ submission.get_status_display }}</td>
                        <!-- <td id="action{{ submission.id }}" colspan="2" class="action">
                    {% if submission.is_under_review %}
                    <a data-id="{{ submission.id }}" class="waves-effect waves-light green accent-4 btn-small accept-submission">
                        <i class="material-icons left">check</i>
                        Accept
                    </a>
                    <a data-id="{{ submission.id }}" class="waves-effect waves-light red darken-1 btn-small reject-submission">
                        <i class="material-icons left">clear</i>
                        Reject
                    </a>
                    {% endif %}
                </td> -->
                    </tr>
                {% endfor %}
            </table>
        </div>

        {% if is_paginated %}
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="waves-effect"><a href="?{{ search_params }}page={{ page_obj.previous_page_number }}">
                        <b><i class="material-icons">chevron_left</i></b>
                    </a></li>
                {% else %}
                    <li class="disabled "><a href="#"><i class="material-icons">chevron_left</i></a></li>
                {% endif %}
                {% if page_obj.number|add:"-4" > 1 %}
                    <li class="waves-effect"><a href="?{{ search_params }}page={{ page_obj.number|add:'-5' }}">2</a></li>
                {% endif %}
                {% for i in page_obj.paginator.page_range %}
                    {% if page_obj.number == i %}
                        <li class="active"><a href="?{{ search_params }}page={{ i }}">{{ i }}</a></li>
                    {% else %}
                        <li class="waves-effect"><a href="?{{ search_params }}page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.paginator.num_pages > page_obj.number|add:'4' %}
                    <li><a href="?{{ search_params }}page={{ page_obj.number|add:'5' }}">. . .</a></li>
                {% endif %}
                {% if page_obj.has_next %}
                    <li class="waves-effect"><a href="?{{ search_params }}page={{ page_obj.next_page_number }}">
                        <b><i class="material-icons">chevron_right</i></b>
                    </a></li>
                {% else %}
                    <li class="disabled "><a href="#"><i class="material-icons">chevron_right</i></a></li>
                {% endif %}
            </ul>
        {% endif %}
    {% else %}
        <div class="section"></div>
        <h5 class="center">No results</h5>
    {% endif %}

{% endblock %}

{% block extra_css_js %}
    <style>
        .table-wrapper {
            margin: 20px;
            border-radius: 10px;
        }

        .table-wrapper table {

            padding: 10px;
        }

        .action {
            text-align: center;
        }
    </style>
    <script>
        let glob_status_url = "{% url 'submission:status_update' %}";
        let glob_csrf_token = "{{ csrf_token }}";
        let preloader = '<div class="preloader-wrapper small active"><div class="spinner-layer spinner-blue-only"><div class="circle-clipper left"><div class="circle"></div></div><div class="gap-patch"><div class="circle"></div></div><div class="circle-clipper right"><div class="circle"></div></div></div></div>'
    </script>
    <script>
        $(document).ready(function () {
            $('select').formSelect();
        });
    </script>
{% endblock %}

bat_roost/templates/submission/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block head_title %}{% endblock %}</title>
    <!-- CSS only -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    {% block extra_head %}
    {% endblock %}

</head>

<body class="yellow lighten-5">


<nav class="teal accent-3">
    <div class="nav-wrapper teal accent-3 ">
        <a href="#" data-target="mobile-sidenav" class="sidenav-trigger left"><i class="material-icons">menu</i></a>

        <a href="{% url 'submission:AllSubmissionView' %}" class="brand-logo ">
            <img src="{% static 'img/bcit_logo_with_text.png' %}" alt="logo" style="height:64px">
        </a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li>
                <a class="nav-link black-text" href="{% url 'submission:AllSubmissionView' %}">All Submission</a>
            </li>
            <li class="nav-item">
                <a class="nav-link black-text" href="{% url 'core:download_user' %}?{{ search_params }}">Download
                    Users</a>
            </li>
            <li class="nav-item">
                <a class="nav-link black-text" href="{% url 'submission:DownloadSubmission' %}?{{ search_params }}">DownloadCSV</a>
            </li>
            {% if search_params %}
                <li class="nav-item">
                    <a class="nav-link black-text" href="{% url 'submission:loc' %}?{{ search_params }}">Filtered
                        locations</a>
                </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link black-text" href="{% url 'submission:loc' %}">All locations</a>
            </li>
        </ul>
    </div>

</nav>
<ul class="sidenav teal accent-3" id="mobile-sidenav">
    <li>
        <a class="nav-link black-text" href="{% url 'submission:AllSubmissionView' %}">All Submission</a>
    </li>
    <li>
        <div class="divider black"></div>
    </li>
    <li class="nav-item">
        <a class="nav-link black-text"
           href="{% url 'submission:DownloadSubmission' %}?{{ search_params }}">DownloadCSV</a>
    </li>
    <li class="nav-item">
        <a class="nav-link black-text" href="{% url 'core:download_user' %}?{{ search_params }}">Download
            Users</a>
    </li>
    <li>
        <div class="divider black"></div>
    </li>
    {% if search_params %}
        <li class="nav-item">
            <a class="nav-link black-text" href="{% url 'submission:loc' %}?{{ search_params }}">Filtered
                locations</a>
        </li>
        <li>
            <div class="divider black"></div>
        </li>
    {% endif %}
    <li class="nav-item">
        <a class="nav-link black-text" href="{% url 'submission:loc' %}">All locations</a>
    </li>
    <li>
        <div class="divider black"></div>
    </li>
</ul>


<div class=''>
    {% block body_block %}
    {% endblock %}
</div>
</body>
{% block extra_css_js %}
{% endblock %}
<script>
    document.addEventListener('DOMContentLoaded', function () {
        var elems = document.querySelectorAll('.sidenav');
        var instances = M.Sidenav.init(elems, {});
    });
</script>
</html>

bat_roost/templates/submission/loc.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <title>Markers Map</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" type="text/css" href="{% static 'map.css' %}">
  <link rel="stylesheet" type="text/css" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css">
  <style type="text/css">
    html, body {
        height: 100%;
        margin: 0;
      }
      #map {
        width: 100%;
        height: 100%;
      }
</style>
  <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
</head>
<body>


    <h3>Marked Locations</h3>
    {{ markers|json_script:"markers-data" }}
    <div id="map"></div>


  <script type="text/javascript">
  document.addEventListener("DOMContentLoaded", (event) => {
    const attribution = '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
    const map = L.map('map',{worldCopyJump:true})
    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { attribution: attribution}).addTo(map);
    const markers = JSON.parse(document.getElementById('markers-data').textContent);
    let feature = L.geoJSON(markers).bindPopup(function (layer) {

        console.log(layer.feature.properties.user);
        return "<a href='http://{{ domain }}/submission/all/" + layer.feature.properties.pk + "/'>View details</a>";
    }).addTo(map);
    map.fitBounds(feature.getBounds(), { padding: [100, 100] });
  });
    </script>
</body>
</html>

bat_roost/templates/submission/submit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Submissions</title>
</head>
<body>
    <h1> Submissions </h1>
    {% if submission_list%}
    <table id='submission'  borderstyle>
        {%for submission in submission_list%}
        <tr>
            <th>User    </th>
            <th>Current Status  </th>
            <th>Desciption</th>
            <th>Approx bats</th>
            <th>Submission Time</th>
            
            <th>Photo taken time</th>
            <th> Action </th>
        </tr>
        <tr>
            <td>{{submission.user}}</td>
            <td>{{submission.status}}</td>
            <td>{{submission.description}}</td>
            <td>{{submission.approx_bats}}</td>
            <td>{{submission.submission_time}}</td>
           
            <td>{{submission.photo_taken_time}}</td>
            <td><td><select id="status">
                <option value="Under Review">Under Review</option>
                <option value="Accepted">Accepted</option>
                <option value="Rejected">Rejected</option>
                
              </select></td></td>
        </tr>
        {%endfor%}
    </table>
    {% if is_paginated %}
<ul class="pagination">
{% if page_obj.has_previous %}
    <li>
        <span><a href="?page={{ page_obj.previous_page_number }}">Previous</a></span>
    </li>
{% endif %}
    <li class="">
        <span>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>
    </li>
{% if page_obj.has_next %}
    <li>
        <span><a href="?page={{ page_obj.next_page_number }}">Next</a></span>
    </li>
{% endif %}
</ul>
{% else %}
    <h3>Your Submissions</h3>
    <p>File not yet available</p>
{% endif %}
    
    {%endif%}
    
</body>
</html>